首页图片展示后端接口
dmnqmn/ExMum pull request #18
Opened 2017-09-15 13:01 UTC by woctober

已按 https://github.com/dmnqmn/ExMum/issues/16 该 issue 完成后端接口，请 @Foolyou @dmnqmn 帮 code review 一下

2017-09-16 06:36 UTC, dmnqmn commented on app/Models/Photo.php
> +            $tag[] = array_search($v, self::TAGS_CONF);
@woctober 这块没有对传入的 tags 做验证

2017-09-16 06:45 UTC, woctober commented on app/Models/Photo.php
> +            $tag[] = array_search($v, self::TAGS_CONF);
done

2017-09-16 06:47 UTC, dmnqmn commented on app/Models/Photo.php
> +            $tag[] = array_search($v, self::TAGS_CONF);
我没有问题了，你可以看一下第一个接口，是否能复用这个接口。

2017-09-16 06:52 UTC, dmnqmn commented
@Foolyou 安仔 你抽空继续 review 一下吧

2017-09-16 08:18 UTC, Foolyou commented
PhotoController 里存在一个 getPhotos 还有一个 showPhotos，似乎 getPhotos 是一个冗余的东西。
以及 Photo 的 Model 里也是两份代码，应该是不需要两个的。

2017-09-16 08:21 UTC, Foolyou commented
你是想做首屏十个，其他情况下默认8个的处理？

这是没有必要的，你可以考虑一下，如果我需要 8 个，直接传一个 8 过去，需要 10 个，直接传 10 过去，一份代码就可以搞定了，不需要写两份。

假如说确实想有一个专门用来获取首屏的函数，这个函数也应该去调用一个通用的函数，传一个 10 进去，而不是为此写两份代码。

2017-09-16 08:33 UTC, Foolyou requested changes

2017-09-16 08:33 UTC, Foolyou commented on app/Models/Photo.php
> +            if (array_key_exists($k, self::TAGS_CONF) && $v == 1) {
@dmnqmn PHP 里是不是也尽量用三个等号比较来着？我不太清楚，你看一下这个。

2017-09-16 08:48 UTC, Foolyou requested changes

2017-09-16 08:48 UTC, Foolyou commented on app/Http/Controllers/PhotoController.php
> +            'lastUpdateId' => $lastUpdateId,
这块其实是直接把请求传过来的 lastUpdateId 又传回去了吧，这样的话不就永远是同一个数了吗？

这个意思就是我第一次请求时这个值是 1908，然后你应该返回给我 1900（假如说你反回了八张图）。当然这个不能直接减下去，最合理的方案就是你把拿到的最后一个 photo 的 id 传过来。

2017-09-16 08:54 UTC, Foolyou requested changes

2017-09-16 08:54 UTC, Foolyou commented on app/Models/Photo.php
> +            $tag[] = array_search($v, self::TAGS_CONF);
这里有一个改进的小建议：

每一个值都去搜一遍其实是不太好看的，提供一种解决方案：
除了 tagId -> tagName 的映射，反过来记录一个 tagName -> tagId 的映射，这个映射你直接写在代码里也好，或者是在运行时通过前者生成也好（如果运行时生成的话最好是将结果放到 cache 里）。
这样你在查的时候就不需要去 search 了，直接从 tagName -> tagId 的映射里取就好了。

2017-09-18 06:05 UTC, woctober commented
>这块其实是直接把请求传过来的 lastUpdateId 又传回去了吧，这样的话不就永远是同一个数了吗？

这个改好了。
现在有个问题就是取不到lastUpdateId的时候，返回的是null。这块你有什么要求么？

2017-09-18 06:06 UTC, Foolyou commented
取不到 lastUpdateId，如果是在 Model 的函数里，可以返回 null。
如果是 Controller 里，默认返回最新的数据吧。

2017-09-18 09:11 UTC, merged